In [ ]:

import pandas as pd
data = {'Name':['Tom','Nick','Krish','jack'],
        'Age': [20,21,19,18]}

df = pd.DataFrame(data)


print(df)

    Name  Age
0    Tom   20
1   Nick   21
2  Krish   19
3   jack   18


In [2]:
import statistics

numbers = [10, 20, 30, 40, 50, 20]
mean_value = statistics.mean(numbers)
median_value = statistics.median(numbers)
mode_value = statistics.mode(numbers)
variance_value = statistics.variance(numbers)
std_deviation = statistics.stdev(numbers)

print("Mean:", mean_value)
print("Median:", median_value)
print("Mode:", mode_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_deviation)


Mean: 28.333333333333332
Median: 25.0
Mode: 20
Variance: 216.66666666666666
Standard Deviation: 14.719601443879744


In [3]:
import statistics

numbers = [10, 20, 30, 40, 50, 20]
mean_value = statistics.mean(numbers)
median_value = statistics.median(numbers)
mode_value = statistics.mode(numbers)
variance_value = statistics.variance(numbers)
std_deviation = statistics.stdev(numbers)

print("Mean:", mean_value)
print("Median:", median_value)
print("Mode:", mode_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_deviation)


Mean: 28.333333333333332
Median: 25.0
Mode: 20
Variance: 216.66666666666666
Standard Deviation: 14.719601443879744


In [4]:
import pandas as pd

data = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age': [27, 24, 22, 32],
        'Address': ['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}

df = pd.DataFrame(data)

print(df[['Name', 'Qualification']])

     Name Qualification
0     Jai           Msc
1  Princi            MA
2  Gaurav           MCA
3    Anuj           Phd


In [5]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Multiplication:\n", A @ B)
print("Transpose of A:\n", A.T)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]


In [6]:

import numpy as np

arr = np.random.randint(0, 101, 10)
print("Array:", arr)
print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())
print("Minimum:", arr.min())
print("Maximum:", arr.max())

Array: [67 65 30  8 81 76  5 71 97 52]
Mean: 55.2
Standard Deviation: 29.535741060620097
Minimum: 5
Maximum: 97


In [7]:
import numpy as np
from scipy import stats
data = np.array([10, 12, 9, 11, 10, 13, 12, 8])
mean_value = stats.tmean(data)
print("Mean:", mean_value)
t_stat, p_value = stats.ttest_1samp(data, 10)
print("T-Statistic:", t_stat)
print("P-Value:", p_value)


Mean: 10.625
T-Statistic: 1.0491086363278161
P-Value: 0.3289933105840345


In [8]:

from scipy import integrate
import numpy as np
def f(x):
    return x**2
result, error = integrate.quad(f, 0, 3)

print("Definite Integration Result:", result)
print("Estimated Error:", error)


Definite Integration Result: 9.000000000000002
Estimated Error: 9.992007221626411e-14


In [9]:

from scipy import optimize
def f(x):
    return x**2 + 4*x + 4
result = optimize.minimize(f, x0=0)
print("Minimum Value:", result.fun)
print("At x =", result.x)

Minimum Value: 0.0
At x = [-2.00000002]
