1. Write a Python program to calculate the following for a given list of numbers:
•	Mean
•	Median
•	Mode
•	Variance
•	Standard Deviation


In [2]:
import statistics
import math

numbers = [10,20,30,40,50,20]

mean = sum(numbers)/ len(numbers)
median = statistics.median(numbers)
mode = statistics.mode(numbers)
variance = statistics.variance(numbers)
std_dev = statistics.stdev(numbers)

print("Mean:", mean)
print("Median:", median)
print("Mode:", mode)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Mean: 28.333333333333332
Median: 25.0
Mode: 20
Variance: 216.66666666666666
Standard Deviation: 14.719601443879744


Create a NumPy array and perform the following operations:
•	Find sum and mean
•	Find maximum and minimum
•	Reshape the array
•	Perform element-wise multiplication


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Sum and Mean
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

# Max and Min
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

# Reshape
reshaped = arr.reshape(2, 3)
print("Reshaped Array:\n", reshaped)

# Element-wise multiplication
print("Element-wise multiplication:\n", reshaped * 2)

Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1
Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Element-wise multiplication:
 [[ 2  4  6]
 [ 8 10 12]]


. Write a Python program to:
•	Create two matrices
•	Perform addition and subtraction
•	Perform matrix multiplication
•	Find transpose of a matrix


In [4]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
print("Addition:\n", A + B)

# Subtraction
print("Subtraction:\n", A - B)

# Matrix Multiplication
print("Multiplication:\n", np.dot(A, B))

# Transpose
print("Transpose of A:\n", A.T)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]


4. Generate a random array of 10 numbers and calculate:
•	Mean
•	Standard deviation
•	Minimum and Maximum value


In [5]:
import numpy as np

arr = np.random.rand(10)  # 10 random numbers

print("Array:", arr)
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))

Array: [0.37123507 0.84034083 0.31280368 0.02058031 0.7127986  0.84401074
 0.99994449 0.60751515 0.21592793 0.76312053]
Mean: 0.5688277328363921
Standard Deviation: 0.3041357287384461
Minimum: 0.020580306415218574
Maximum: 0.9999444934215931


5. Write a Python program using SciPy to:
•	Calculate mean using scipy.stats
•	Perform a t-test on a sample dataset


In [6]:
from scipy import stats
import numpy as np

data = np.array([10, 12, 14, 16, 18])

# Mean using scipy
mean = stats.tmean(data)
print("Mean:", mean)

# One sample t-test (test mean = 12)
t_stat, p_value = stats.ttest_1samp(data, 12)

print("T-statistic:", t_stat)
print("P-value:", p_value)

Mean: 14.0
T-statistic: 1.414213562373095
P-value: 0.23019964108049873


6. Write a Python program to compute definite integration of a mathematical function using scipy.integrate.

In [7]:
from scipy import integrate
import numpy as np

# Define function
def f(x):
    return x**2

# Integrate from 0 to 5
result, error = integrate.quad(f, 0, 5)

print("Integration Result:", result)

Integration Result: 41.66666666666666


7. Write a Python program to minimize a mathematical function using scipy.optimize.

In [8]:
from scipy import optimize

# Function to minimize
def f(x):
    return x**2 + 4*x + 4

result = optimize.minimize(f, 0)

print("Minimum Value:", result.fun)
print("At x =", result.x)

Minimum Value: 0.0
At x = [-2.00000002]
